sudo: required
services:
  - docker

before_install:
  - docker build -t brutebeer/docker-react-proj -f Dockerfile.dev .

script:
  - docker run brutebeer/docker-react-proj npm run test -- --coverage
